services:
  meilisearch:
    image: 'getmeili/meilisearch:v1.2'
    environment:
      - 'MEILI_ENV=development'
    ports:
      - '7700'
    # mount
    volumes:
      - './data/meilisearch/data:/meili_data'
  #  elasticsearch:
  #    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.7.1'
  #    environment:
  #      - 'ELASTIC_PASSWORD=secret'
  #      - 'discovery.type=single-node'
  #      - 'xpack.security.enabled=false'
  #    ports:
  #      - '9200'
  #      - '9300'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sapling'
      - 'MYSQL_PASSWORD=sapling'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=sapling'
    ports:
      - '36336:3306'
    volumes:
      - './data/mysql/etc/mysql/conf.d:/etc/mysql/conf.d'
      - './data/mysql/var/lib/mysql:/var/lib/mysql'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=sapling'
      - 'RABBITMQ_DEFAULT_USER=sapling'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
