server:
  port: 8081
sa-token:
  token-name: sapling-token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-128
  is-log: true
logging:
  level:
    com.github.bitsapling.sapling: debug
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://direct.ghostchu.com:3306/sapling?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: sapling
    password: sapling
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    redis:
      cache-null-values: true
      key-prefix: sapling
      time-to-live: 86400
      enable-statistics: true
      use-key-prefix: true
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: sapling_scheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            useProperties: false
            clusterCheckinInterval: 10000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  data:
    redis:
      database: 3
      timeout: 3000
      password: 123456
      port: 6379
      host: localhost
      repositories:
        enabled: false
      jedis:
        pool:
          max-idle: 8
          min-idle: 2
          max-active: 8
          max-wait: -1