spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:36336/sapling?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: sapling
    password: sapling
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 16379
  session:
    store-type: redis
    timeout: 8H
    redis:
      namespace: spring:sapling-session
      cleanup-cron: 10 * * * * *
      save-mode: ON_SET_ATTRIBUTE
      flush-mode: ON_SAVE
      repository-type: default