redis:
  host: localhost
  port: 6379
  database: 3
spring:
  profiles:
    active: test,caching,db-tencentcloud
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        generate-ddl: true
        hbm2ddl:
          auto: update
  data:
    redis:
      database: ${redis.database}
      timeout: 3000
      port: ${redis.port}
      host: ${redis.host}
      jedis:
        pool:
          max-idle: 8
          min-idle: 2
          max-active: 8
          max-wait: -1
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: sapling_scheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
            clusterCheckinInterval: 10000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB
server:
  port: 8081
  servlet:
    context-path: /api
sa-token:
  token-name: sapling-token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-128
