spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:36336/sapling?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: sapling
    password: sapling
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 16379
  session:
    store-type: redis
    timeout: 8H
    redis:
      namespace: spring:sapling-session
      cleanup-cron: 10 * * * * *
      save-mode: ON_SET_ATTRIBUTE
      flush-mode: ON_SAVE
      repository-type: indexed
mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: "logic_deleted"
#  rabbitmq:
#    addresses: 192.168.100.120:5672,192.168.100.121:5672,192.168.100.122:5672
#    username: admin
#    password: admin
#    publisher-returns: true
#    publisher-confirm-type: correlated
#    virtual-host: /
#    listener:
#      type: simple
#      simple:
#        acknowledge-mode: auto
#        prefetch: 1
#        concurrency: 3
#        max-concurrency: 3
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 3000