spring:
  jpa:
    properties:
      redisson-config: classpath:conf/redisson.yaml
      hibernate:
        cache:
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_second_level_cache: true
          use_query_cache: true
          region_prefix: sapling
          use_structured_entries: true
          provider_configuration_file_resource_path: classpath:conf/hibernate-redis.properties
  cache:
    redis:
      cache-null-values: true
      key-prefix: sapling
      time-to-live: 86400
      enable-statistics: true
      use-key-prefix: true
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine #other choose：caffeine
      keyConvertor: jackson #other choose：fastjson/jackson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: jackson #other choose：fastjson/jackson
      broadcastChannel: sapling
      valueEncoder: java #other choose：kryo/kryo5
      valueDecoder: java #other choose：kryo/kryo5
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${redis.host}
      port: ${redis.port}