spring:
  jpa:
    properties:
      redisson-config: classpath:conf/redisson.yaml
      hibernate:
        cache:
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_second_level_cache: true
          use_query_cache: true
          region_prefix: sapling
          use_structured_entries: true
          provider_configuration_file_resource_path: classpath:conf/hibernate-redis.properties
  cache:
    redis:
      cache-null-values: true
      key-prefix: sapling
      time-to-live: 86400
      enable-statistics: true
      use-key-prefix: true
  data:
    redis:
      database: 3
      timeout: 3000
      password: 123456
      port: 6379
      host: localhost
      repositories:
        enabled: false
      jedis:
        pool:
          max-idle: 8
          min-idle: 2
          max-active: 8
          max-wait: -1