spring:
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
  cache:
    redis:
      cache-null-values: true
      key-prefix: sapling
      time-to-live: 86400
      enable-statistics: true
      use-key-prefix: true
  data:
    redis:
      database: 3
      timeout: 3000
      password: 123456
      port: 6379
      host: localhost
      repositories:
        enabled: false
      jedis:
        pool:
          max-idle: 8
          min-idle: 2
          max-active: 8
          max-wait: -1