spring:
  profiles:
    active: test,db-tencentcloud
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        generate-ddl: true
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: sapling_scheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            useProperties: false
            clusterCheckinInterval: 10000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
server:
  port: 8081
sa-token:
  token-name: sapling-token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-128
