sa-token:
  is-log: true
logging:
  level:
    com.github.bitsapling.sapling: debug
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect