spring:
  profiles:
    active: test,db-tencentcloud
  jpa:
    properties:
      redisson-config: classpath:conf/redisson.yaml
      hibernate:
        cache:
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          use_second_level_cache: true
          use_query_cache: true
          region_prefix: sapling
          use_structured_entries: true
          provider_configuration_file_resource_path: classpath:conf/hibernate-redis.properties
        ddl-auto: update
        generate-ddl: true
        hbm2ddl:
          auto: update
  quartz:
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: sapling_scheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            useProperties: false
            clusterCheckinInterval: 10000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
server:
  port: 8081
sa-token:
  token-name: sapling-token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-128
